---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: florps.jgaskins.wtf
spec:
  group: jgaskins.wtf
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                name:
                  type: string
                id:
                  type: string
                count:
                  type: integer
  scope: Namespaced
  names:
    plural: florps
    singular: florp
    kind: Florp
    shortNames:
      - fl
